# Generated by Django 4.2.6 on 2023-10-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_biodata'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
